version: '3.3'

volumes:
  db_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db_new
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: vasiyats/foodgram_back
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: vasiyats/foodgram_front
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: vasiyats/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media