# Generated by Django 3.2.3 on 2024-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20241117_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='full_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
