# Generated by Django 3.2.3 on 2024-11-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_full_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='full_url',
        ),
    ]
