# Generated by Django 3.2.3 on 2024-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_recipe_full_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(editable=False, max_length=3, unique=True)),
                ('original_url', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
