# Generated by Django 3.2.3 on 2024-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20241121_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeShortLink',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(default=0, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
